[package]
name = "os"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
common = { path = "../common" }
winit = "0.24"
thiserror = "1.0"
tracing = "0.1"
