[package]
name = "graphics"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
common = { path = "../core/common" }
os = { path = "../core/os" }
gfx = { path = "../core/gfx" }
gui_widget = { path = "../core/gui_widget" }
app = { path = "../core/app" }
wgpu = "0.7"
egui = "0.11"
image = { version = "0.23", default-features = false, features = ["bmp"] }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
ultraviolet = { version = "0.8", features = ["bytemuck"] }
bytemuck = { version = "1.5", features = ["derive"] }
tracing = "0.1"

[build-dependencies]
gfxc = { path = "../core/gfxc" }
