[package]
name = "gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
common = { path = "../../core/common" }
egui.workspace = true
ultraviolet.workspace = true
