[package]
name = "gui"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
common = { path = "../../core/common" }
os = { path = "../../core/os" }
gfx = { path = "../../core/gfx" }
egui = "0.11"
wgpu = "0.8"
bytemuck = { version = "1.5", features = ["derive"] }
thiserror = "1"

[build-dependencies]
gfxc = { path = "../../core/gfxc" }
