cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "core/common",
  "core/os",
  "core/gfx",
  "core/gfxc",
  "core/app",
  "graphics/triangle",
  "graphics/quads"
]

# Development profile: full debug information, some optimisations.
[profile.dev]
opt-level = 2
overflow-checks = true
debug-assertions = true
panic = "abort"
debug = true
split-debuginfo = "unpacked"
codegen-units = 8
lto = false
incremental = true

# Fast development profile: no debug information, some optimisations.
[profile.fastdev]
inherits = 'dev'
opt-level = 2
debug = false
# Fully optimize all dependencies, but not our own crates, to speed up compilation.
[profile.fastdev.package."*"]
opt-level = 3
[profile.fastdev.package."common"]
opt-level = 2
[profile.fastdev.package."os"]
opt-level = 2
[profile.fastdev.package."gfx"]
opt-level = 2
[profile.fastdev.package."gfxc"]
opt-level = 2
[profile.fastdev.package."app"]
opt-level = 2
[profile.fastdev.package."triangle"]
opt-level = 2
[profile.fastdev.package."quads"]
opt-level = 2

[profile.test]
inherits = 'fastdev'

# Release profile: full optimisations, including link-time optimisations.
[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false

# Performance profiling profile: full debug information, full optimisations.
[profile.profile]
inherits = 'release'
debug = true
