[workspace]
members = [
  "core/*",
  "gadgets",
  "graphics",
]
default-members = [
  "core/*",
  "graphics",
  "gadgets",
]
resolver = "2"

[workspace.dependencies]
raw-window-handle = "0.6"
wgpu = "0.19"
egui = "0.18"
