cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "core/*",
  "graphics",
  "graphics/voxel_meshing"
]
default-members = [
  "graphics",
  "graphics/voxel_meshing"
]
resolver = "2"

# Development profile: no debug information, some optimisations.
[profile.dev]
opt-level = 2
debug = false
debug-assertions = true
overflow-checks = true
lto = false
panic = "abort"
incremental = true
# Optimize all dependencies, but not our own crates, to speed up runtime.
[profile.dev.package."*"]
opt-level = 3
debug = false
overflow-checks = true
debug-assertions = true
incremental = true

# Testing: same as development profile.
[profile.test]
inherits = "dev"

# Debug profile: full debug information, no optimisations.
[profile.dbg]
inherits = "dev"
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "abort"
incremental = true
# Optimize all dependencies, but not our own crates, to speed up runtime.
[profile.dbg.package."*"]
opt-level = 3
debug = true
overflow-checks = true
debug-assertions = true
incremental = true

# Release profile: full optimisations, including full LTO.
[profile.release]
opt-level = 3
debug = false
overflow-checks = false
debug-assertions = false
lto = true
panic = "abort"

# Benchmarking profile: full optimisations, including full LTO.
[profile.bench]
inherits = "release"

# Fast benchmarking profile: full optimisations, but with thin LTO and incrementality enabled.
[profile.fastbench]
inherits = "release"
incremental = true
codegen-units = 256
lto = "thin"

# Performance profiling profile: full debug information, full optimisations.
[profile.profile]
inherits = "release"
debug = true
