[package]
name = "gui_widget"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
common = { path = "../../core/common" }
egui = "0.11"
ultraviolet = "0.8"
