[package]
name = "gui_widget"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../../core/common" }
egui = { workspace = true }
ultraviolet = "0.9"
