[package]
name = "app"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
math = { path = "../math" }
util = { path = "../util" }
os = { path = "../os" }
gfx = { path = "../gfx" }
wgpu = "0.7"
raw-window-handle = "0.3"
dotenv = "0.15"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-log = "0.1"
