[package]
name = "gfx"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../../core/common" }
wgpu = { workspace = true }
egui = { workspace = true, optional = true }
gui_widget = { path = "../../core/gui_widget", optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
image = { workspace = true, default-features = false }
ultraviolet.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
profiling.workspace = true

[build-dependencies]
gfxc = { path = "../gfxc" }

[features]
default = ["serde", "debugging_gui"]
serde = ["dep:serde", "common/serde", "egui/serde", "ultraviolet/serde"]
debugging_gui = ["egui", "gui_widget"]
