[package]
name = "gfx"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
common = { path = "../../core/common" }
gui_widget = { path = "../../core/gui_widget" }
wgpu = "0.8"
raw-window-handle = "0.3"
egui = "0.11"
image = { version = "0.23", default-features = false }
ultraviolet = "0.8"
bytemuck = "1.5"
thiserror = "1"
