[package]
name = "gfx"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../../core/common" }
wgpu = "0.12"
raw-window-handle = "0.4"
egui = { version = "0.18", features = ["serde"], optional = true }
gui_widget = { path = "../../core/gui_widget", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
image = { version = "0.23", default-features = false }
ultraviolet = "0.8"
bytemuck = "1.5"
thiserror = "1"

[build-dependencies]
gfxc = { path = "../gfxc" }

[features]
default = ["debugging_gui", "serde"]
debugging_gui = ["egui", "gui_widget"]
