[package]
name = "gfx"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
math = { path = "../math" }
wgpu = "0.7"
raw-window-handle = "0.3"
bytemuck = "1.5"
thiserror = "1"
