[package]
name = "gfx"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../../core/common" }
raw-window-handle = { workspace = true }
wgpu = { workspace = true }
egui = { workspace = true, optional = true }
gui_widget = { path = "../../core/gui_widget", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
image = { version = "0.23", default-features = false }
ultraviolet = "0.9"
bytemuck = "1.5"
thiserror = "1"
profiling = "1"

[build-dependencies]
gfxc = { path = "../gfxc" }

[features]
default = ["serde", "debugging_gui"]
serde = ["dep:serde", "common/serde", "egui/serde", "ultraviolet/serde"]
debugging_gui = ["egui", "gui_widget"]
