[package]
name = "gfxc"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
naga = { version = "0.20", features = ["glsl-in", "spv-out"] }
bytemuck = "1.16"
walkdir = "2.5"
regex = "1"
anyhow = "1"
