[package]
name = "gfxc"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
shaderc = "=0.7.3"
shaderc-sys = "=0.7.3"
walkdir = "2.3"
