[package]
name = "gfxc"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
naga = { workspace = true, features = ["glsl-in", "spv-out"] }
bytemuck.workspace = true
walkdir = "2"
regex = "1"
anyhow = "1"
