[package]
name = "job_queue"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
flume = "0.10"
petgraph = { version = "0.6", default-features = false, features = ["graphmap"] }
smallvec = { version = "1", features = ["const_generics"] }
rustc-hash = "1"
tracing = "0.1"
profiling = "1"
