[package]
name = "job_queue"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5"
petgraph = { version = "0.6", default-features = false, features = ["stable_graph"] }
tracing = "0.1"
